# Runtime operator resolves the published image to an immutable ECR digest.
FROM quay.io/keycloak/keycloak:26.7.3
COPY deploy/runtime/identity/realm.json /opt/keycloak/data/import/redsim-realm.json
ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
CMD ["start", "--import-realm"]
