"""ML finding projections and follow-up action admissions.

The campaign record is the evidence authority. Follow-up actions are admitted
as child campaigns so they produce immutable evidence through the same worker.

Projection contract (spec 5.7): the worker writes ``RedsimFinding.model_dump()``
into ``Finding.schema_blob`` with ``finding_type="adversarial_ml"`` and the
``MLFindingDetail.model_dump()`` block at ``schema_blob["ml"]``; the API reads
that block back with ``MLFindingDetail.model_validate``. Every field is derived
from measured rows of the campaign record. Nothing is generated by an LLM here.
"""

from __future__ import annotations

import hashlib
import json
import logging
import math
from collections.abc import Iterable, Iterator, Mapping, Sequence
from dataclasses import dataclass
from datetime import UTC, datetime
from typing import TYPE_CHECKING, Any, Literal, cast, get_args
from uuid import uuid4

from redsim.ml.schema import (
    CampaignRecord,
    CandidateRecommendation,
    FindingReview,
    Interpretation,
    Measurement,
    MLFindingDetail,
    Observation,
)
from redsim.ml.scoring import finding_inputs
from redsim.safety import authorize
from redsim.schema import FindingType, RedsimFinding

if TYPE_CHECKING:
    from sqlalchemy.orm import Session

    from redsim.audit.chain import AuditWriter
    from redsim.config import RedsimConfig
    from redsim.ml.scoring import FindingInputs

logger = logging.getLogger(__name__)


_TERMINAL = {"succeeded", "failed", "cancelled"}
_SUPPORTED_MODALITIES = {"image", "tabular"}
# Spec 6.4: the only user-owned transition is ``open | failed -> false_positive``.
DISMISSABLE_FROM: frozenset[str] = frozenset({"open", "failed"})
DISMISSED_STATUS = "false_positive"

# Campaign-level artifact kinds that belong on every finding of the run (spec 5.7:
# robustness curve and the campaign SHAP artifacts). Both the spec 5.8 names and the
# names the worker's artifact sink derives from file names are accepted.
_CAMPAIGN_ARTIFACT_KINDS: frozenset[str] = frozenset({
    "ml.curve",
    "ml.shap.summary", "ml.shap.summary_text", "ml.shap_summary",
    "ml.shap.bar", "ml.shap.beeswarm",
    "ml.shap_bar_clean", "ml.shap_bar_adv", "ml.shap_beeswarm_clean", "ml.shap_beeswarm_adv",
})


class MLFindingAdmissionError(Exception):
    """A stable error returned by the ML finding admission routes."""

    def __init__(self, code: str, message: str, *, phase: str | None = None) -> None:
        super().__init__(message)
        self.code, self.phase = code, phase


@dataclass(frozen=True)
class FindingJobHandle:
    run_id: str
    job_ids: list[str]

    def to_response(self) -> dict[str, Any]:
        return {"run_id": self.run_id, "job_ids": self.job_ids,
                "status_url": f"/v1/runs/{self.run_id}"}


# ---------------------------------------------------------------------------
# Projection helpers (pure functions over the campaign record)
# ---------------------------------------------------------------------------


def _same_eps(a: float | None, b: float | None) -> bool:
    return a is not None and b is not None and math.isclose(float(a), float(b), rel_tol=0.0, abs_tol=1e-12)


def _eps_of(measurement: Measurement) -> float | None:
    value = measurement.params.get("eps")
    return float(value) if isinstance(value, (int, float)) and not isinstance(value, bool) else None


def _fraction(numerator: int | None, denominator: int | None) -> str:
    if numerator is None or denominator is None:
        return "not recorded"
    return f"{numerator}/{denominator}"


def _rate(value: float | None) -> str:
    return "not computed" if value is None else f"{float(value):.4f}"


def finding_measurements(campaign: CampaignRecord, attack_id: str) -> list[Measurement]:
    """Spec 5.7: the clean row, this attack's rows per eps and the control rows per eps."""
    return [m for m in campaign.measurements
            if m.family in ("clean", "control") or m.attack_id == attack_id]


def _first_explained_attack(campaign: CampaignRecord, in_scope: Sequence[str]) -> str | None:
    """The first in-scope attack whose reference row carries explain-stage fields.

    The campaign runner numbers observations ``o.NNN`` per attack and suffixes
    ``.<attack_id>`` only on a collision, so the bare ids belong to the first
    attack that was explained. The reference row is the only row the explain
    stage fills (spec 13.5), which is how "was explained" is recognised.
    """
    for aid in in_scope:
        for m in campaign.measurements:
            if m.family == "evasion" and m.attack_id == aid and (
                m.expl_shift_n is not None or m.expl_shift_mean is not None
            ):
                return aid
    return in_scope[0] if in_scope else None


def _observation_owner(obs_id: str, in_scope: Sequence[str], bare_owner: str | None) -> str | None:
    for aid in in_scope:
        if obs_id.endswith(f".{aid}"):
            return aid
    return bare_owner


def finding_observations(campaign: CampaignRecord, attack_id: str) -> list[Observation]:
    """Observations attributed to ``attack_id`` by the runner's id scheme (see above)."""
    in_scope = list(dict.fromkeys(campaign.config.attack_ids))
    bare_owner = _first_explained_attack(campaign, in_scope)
    return [o for o in campaign.observations
            if _observation_owner(o.id, in_scope, bare_owner) == attack_id]


def _cites(ids: Iterable[str], mine: set[str], others: set[str]) -> bool:
    """A statement belongs to this finding when it cites this attack's evidence, or when
    it cites only shared evidence (clean and control rows) and nothing of another attack."""
    cited = set(ids)
    if cited & mine:
        return True
    return not (cited & others)


def _finding_statements(
    campaign: CampaignRecord, attack_id: str, observations: Sequence[Observation],
) -> tuple[list[Interpretation], list[CandidateRecommendation]]:
    in_scope = list(dict.fromkeys(campaign.config.attack_ids))
    bare_owner = _first_explained_attack(campaign, in_scope)
    mine = {m.id for m in campaign.measurements if m.family == "evasion" and m.attack_id == attack_id}
    mine |= {o.id for o in observations}
    others = {m.id for m in campaign.measurements
              if m.family == "evasion" and m.attack_id is not None and m.attack_id != attack_id}
    others |= {o.id for o in campaign.observations
               if _observation_owner(o.id, in_scope, bare_owner) != attack_id}
    interpretation = [i for i in campaign.interpretation if _cites(i.basis, mine, others)]
    mine |= {i.id for i in interpretation}
    others |= {i.id for i in campaign.interpretation if i not in interpretation}
    recommendations = [r for r in campaign.recommendations if _cites(r.triggered_by, mine, others)]
    return interpretation, recommendations


def _evasion_row(measurements: Sequence[Measurement], attack_id: str, eps: float | None) -> Measurement | None:
    if eps is None:
        return None
    for m in measurements:
        if m.family == "evasion" and m.attack_id == attack_id and _same_eps(_eps_of(m), eps):
            return m
    return None


def _control_row(measurements: Sequence[Measurement], eps: float) -> Measurement | None:
    for m in measurements:
        if m.family == "control" and _same_eps(_eps_of(m), eps):
            return m
    return None


def finding_title(attack_name: str, norm: str, inputs: FindingInputs, first_row: Measurement | None) -> str:
    """Spec 5.7 / 15.5 title: attack, first-success eps, norm and the ASR fraction."""
    eps_text = f"{float(inputs.first_success_eps):g}" if inputs.first_success_eps is not None else "n/a"
    flipped = first_row.n_flipped_from_clean if first_row is not None else None
    denominator = (first_row.n_clean_correct if first_row is not None and first_row.n_clean_correct is not None
                   else inputs.n_clean_correct)
    return (f"{attack_name} flips predictions at ε={eps_text} ({norm}; "
            f"ASR {_fraction(flipped, denominator)})")


def finding_description(
    campaign: CampaignRecord, attack_id: str, attack_name: str, inputs: FindingInputs,
    measurements: Sequence[Measurement],
) -> str:
    """Rules-generated measured summary citing measurement ids (spec 5.7). No LLM."""
    config = campaign.config
    ref = float(config.reference_eps)
    clean = next((m for m in measurements if m.family == "clean"), None)
    first_row = _evasion_row(measurements, attack_id, inputs.first_success_eps)
    ref_row = _evasion_row(measurements, attack_id, ref)
    control = _control_row(measurements, ref)
    parts: list[str] = []
    if first_row is not None and inputs.first_success_eps is not None:
        parts.append(
            f"Measured: {attack_name} ({attack_id}, {config.norm}) first crossed the finding threshold "
            f"(ASR >= {inputs.threshold:g}) at eps={float(inputs.first_success_eps):g}, flipping "
            f"{_fraction(first_row.n_flipped_from_clean, first_row.n_clean_correct)} clean-correct samples "
            f"[{first_row.id}]."
        )
    else:
        parts.append(
            f"Measured: {attack_name} ({attack_id}, {config.norm}) crossed the finding threshold "
            f"(ASR >= {inputs.threshold:g}) on the declared eps grid {list(config.eps_grid)}."
        )
    if ref_row is not None:
        parts.append(
            f"At the reference budget eps={ref:g} the attack success rate was "
            f"{_rate(ref_row.attack_success_rate)} "
            f"({_fraction(ref_row.n_flipped_from_clean, ref_row.n_clean_correct)}) and accuracy "
            f"{_fraction(ref_row.n_correct, ref_row.n)} [{ref_row.id}]."
        )
    if clean is not None:
        parts.append(f"Clean accuracy {_fraction(clean.n_correct, clean.n)} [{clean.id}].")
    if control is not None:
        parts.append(
            f"Benign noise control at eps={ref:g}: accuracy {_fraction(control.n_correct, control.n)} "
            f"[{control.id}]."
        )
    parts.append(
        f"Slice: n={config.n_samples}, seed={config.seed}; confidence {inputs.confidence} from "
        f"{inputs.n_clean_correct} clean-correct samples. Measured at these settings only."
    )
    return " ".join(parts)


def finding_remediation_steps(recommendations: Sequence[CandidateRecommendation]) -> str | None:
    """Spec 5.7: ``"CANDIDATE (not evaluated): ..."`` rendering of the rules-layer candidates."""
    if not recommendations:
        return None
    lines = [f"CANDIDATE ({r.validation}): {r.title}. {r.rationale}" for r in recommendations]
    return "\n".join(lines)


def _artifact_name(kind: str, location: str, attack_id: str) -> str | None:
    """A stable display name for a campaign-level artifact, or ``None`` to skip it.

    Locations are ``<project>/<run>/<file name>/<sha256>`` (the sink's key, possibly
    behind a filesystem root or an ``s3://`` prefix), so the file name is the segment
    before the digest. Per-attack curve files of another attack are skipped.
    """
    segments = [s for s in str(location).replace("\\", "/").split("/") if s]
    file_name = segments[-2] if len(segments) >= 2 and "." in segments[-2] else None
    if kind == "ml.curve":
        if file_name == "robustness_curve.png":
            return "robustness_curve.png"
        if file_name == f"{attack_id}.json":
            return "robustness_curve.json"
        if file_name is not None and file_name.endswith(".json"):
            return None
        return file_name or "robustness_curve"
    return file_name or kind


def _campaign_artifact_ids(session: Session, run_id: str, attack_id: str) -> dict[str, str]:
    from sqlalchemy import select

    from redsim.db.models import Artifact

    rows = session.execute(
        select(Artifact).where(Artifact.run_id == run_id, Artifact.kind.in_(sorted(_CAMPAIGN_ARTIFACT_KINDS)))
        .order_by(Artifact.created_at, Artifact.id)
    ).scalars().all()
    out: dict[str, str] = {}
    for row in rows:
        name = _artifact_name(str(row.kind), str(row.location), attack_id)
        if name is None:
            continue
        if name in out and out[name] != row.id:
            name = f"{name}#{str(row.sha256)[:12]}"
        out[name] = row.id
    return out


def _run_record_artifact_id(session: Session, run_id: str) -> str | None:
    from sqlalchemy import select

    from redsim.db.models import Artifact

    row = session.execute(
        select(Artifact).where(Artifact.run_id == run_id, Artifact.kind == "ml.run_record")
        .order_by(Artifact.created_at.desc(), Artifact.id.desc())
    ).scalars().first()
    return None if row is None else str(row.id)


def build_finding_detail(
    campaign: CampaignRecord, attack_id: str, inputs: FindingInputs, *, artifacts: dict[str, str] | None = None,
) -> MLFindingDetail:
    """The ``MLFindingDetail`` block for one attack of a completed campaign (spec 5.7)."""
    attacks = {attack.id: attack for attack in campaign.attacks}
    info = attacks.get(attack_id)
    measurements = finding_measurements(campaign, attack_id)
    observations = finding_observations(campaign, attack_id)
    interpretation, recommendations = _finding_statements(campaign, attack_id, observations)
    merged: dict[str, str] = {}
    for o in observations:
        for name, artifact_id in o.artifacts.items():
            merged[f"{o.id}:{name}" if name in merged and merged[name] != artifact_id else name] = artifact_id
    merged.update(artifacts or {})
    return MLFindingDetail(
        attack_id=attack_id, attack_name=info.name if info is not None else attack_id,
        norm=campaign.config.norm, eps_grid=list(campaign.config.eps_grid),
        reference_eps=campaign.config.reference_eps,
        first_success_eps=inputs.first_success_eps, asr_at_reference=inputs.asr_at_reference,
        asr_by_eps=inputs.asr_by_eps, threshold=inputs.threshold,
        measurements=measurements, observations=observations,
        interpretation=interpretation, recommendations=recommendations,
        limitations=list(campaign.limitations), artifacts=merged,
    )


def read_finding_detail(schema_blob: dict[str, Any] | None) -> MLFindingDetail | None:
    """Read the ``ml`` block of a stored finding back through the frozen schema."""
    if not schema_blob:
        return None
    block = schema_blob.get("ml")
    if not isinstance(block, dict) or not block:
        return None
    return MLFindingDetail.model_validate(block)


# ---------------------------------------------------------------------------
# Projection
# ---------------------------------------------------------------------------


def project_campaign_findings(session: Session, campaign: CampaignRecord) -> list[str]:
    """Project threshold-crossing attacks from a completed campaign once.

    Existing rows are left untouched.  This matters both for retry safety and
    because a later reviewer/verification update must never be overwritten by
    replaying the immutable campaign record.
    """
    from sqlalchemy import select

    from redsim.db.models import Finding, Run, Target

    if campaign.status not in _TERMINAL:
        raise ValueError("only a terminal CampaignRecord can be projected")
    run = session.get(Run, campaign.run_id)
    if run is None:
        raise LookupError(f"campaign run not found: {campaign.run_id}")
    model_sha = (campaign.provenance.model_sha256 if campaign.provenance else None)
    if not model_sha or not campaign.settings_hash:
        raise ValueError("completed campaign lacks model_sha256 or settings_hash")

    target_row_id = run.target_id or campaign.config.target_id
    target = session.get(Target, target_row_id) if target_row_id else None
    target_value = str(target.value) if target is not None else None
    run_record_id = _run_record_artifact_id(session, campaign.run_id)
    attacks = {attack.id: attack for attack in campaign.attacks}
    projected: list[str] = []
    for attack_id in dict.fromkeys(campaign.config.attack_ids):
        inputs = finding_inputs(campaign.config, campaign.measurements, attack_id)
        if not (inputs.crosses_threshold and inputs.denominator_ok and inputs.severity):
            continue
        scanner_id = f"ml.{attack_id}"
        existing = session.execute(
            select(Finding.id).where(Finding.run_id == campaign.run_id,
                                     Finding.scanner_finding_id == scanner_id)
        ).scalar_one_or_none()
        if existing is not None:
            projected.append(existing)
            continue
        info = attacks.get(attack_id)
        attack_name = info.name if info is not None else attack_id
        detail = build_finding_detail(
            campaign, attack_id, inputs,
            artifacts=_campaign_artifact_ids(session, campaign.run_id, attack_id),
        )
        first_row = _evasion_row(detail.measurements, attack_id, inputs.first_success_eps)
        evidence = {
            "measurements": [m.id for m in detail.measurements],
            "observations": [o.id for o in detail.observations],
            "interpretation": [i.id for i in detail.interpretation],
        }
        now = datetime.now(UTC).isoformat()
        finding = RedsimFinding(
            id=scanner_id,
            title=finding_title(attack_name, campaign.config.norm, inputs, first_row),
            severity=inputs.severity, finding_type="adversarial_ml",
            description=finding_description(campaign, attack_id, attack_name, inputs, detail.measurements),
            source_tool=f"redsim.ml/{attack_id}", source_run_id=campaign.run_id,
            affected_component=str(target_row_id or campaign.target.id), target=target_value,
            confidence=inputs.confidence, status="open", created_at=now, updated_at=now,
            evidence=json.dumps(evidence, sort_keys=True),
            references=list(info.references) if info is not None and info.references else None,
            artifact_path=run_record_id,
            remediation_steps=finding_remediation_steps(detail.recommendations),
        ).model_dump(mode="json")
        finding["ml"] = detail.model_dump(mode="json")
        row = Finding(
            id=str(uuid4()), scanner_finding_id=scanner_id, run_id=campaign.run_id,
            project_id=run.project_id, schema_blob=finding, status="open",
            severity=inputs.severity, source_tool=f"redsim.ml/{attack_id}",
            validation_state="unvalidated",
            dedup_key=f"ml:{model_sha[:16]}:{attack_id}:{campaign.settings_hash[:16]}",
        )
        session.add(row)
        session.flush()
        projected.append(row.id)
    return projected


# ---------------------------------------------------------------------------
# Follow-up actions
# ---------------------------------------------------------------------------


def create_finding_action_job(
    *, finding_id: str, action: Literal["explain", "harden"], body: dict[str, Any],
    actor: str, config: RedsimConfig, audit_writer: AuditWriter,
) -> FindingJobHandle:
    """Audit first, then create one immutable follow-up Run and Job."""
    from sqlalchemy import MetaData, Table, select

    from redsim.db.models import Finding, Job, Run, Target
    from redsim.db.session import get_session
    from redsim.ml.schema import CampaignConfig

    job_type = "explain.run" if action == "explain" else "harden.recommend"
    with get_session() as session:
        finding = session.get(Finding, finding_id)
        if finding is None:
            raise LookupError("finding not found")
        parent = session.get(Run, finding.run_id)
        if parent is None:
            raise LookupError("campaign run not found")
        if parent.status not in _TERMINAL:
            raise MLFindingAdmissionError("campaign_not_terminal",
                                          "the parent campaign is not terminal")
        target = session.get(Target, parent.target_id) if parent.target_id else None
        raw_manifest = getattr(target, "detail", None)
        manifest: dict[str, Any] = (
            raw_manifest if isinstance(raw_manifest, dict) else {}
        )
        nested_value = manifest.get("manifest")
        nested_manifest: dict[str, Any] = (
            nested_value if isinstance(nested_value, dict) else {}
        )
        modality = manifest.get("modality") or nested_manifest.get("modality")
        if modality not in _SUPPORTED_MODALITIES:
            raise MLFindingAdmissionError(
                "not_implemented", "this finding modality has no Phase A action implementation", phase="B")
        candidates = session.execute(
            select(Job).where(Job.project_id == finding.project_id, Job.type == job_type,
                              Job.status.in_(("queued", "running")))
        ).scalars()
        if any((job.detail or {}).get("finding_id") == finding_id for job in candidates):
            raise MLFindingAdmissionError("job_in_flight",
                                          f"a {job_type} job is already in flight for this finding")
        run_id, job_id = f"run-{uuid4().hex[:12]}", f"job-{uuid4().hex[:12]}"
        campaign_table = Table(
            "ml_campaigns", MetaData(), autoload_with=session.get_bind(),
        )
        parent_campaign = session.execute(
            campaign_table.select().where(campaign_table.c.run_id == parent.id)
        ).mappings().one_or_none()
        if parent_campaign is None:
            raise LookupError("campaign record not found")
        snapshot = dict(parent_campaign["config"])
        if action == "explain":
            requested = body.get("explain_k")
            snapshot["explain_k"] = (
                int(requested)
                if requested is not None
                else max(1, int(snapshot.get("explain_k") or 8))
            )
            if body.get("seed") is not None:
                snapshot["seed"] = int(body["seed"])
        else:
            snapshot["auto_recommend"] = True
            snapshot["llm_narrative"] = bool(body.get("llm_narrative", False))
        frozen = CampaignConfig.model_validate(snapshot).model_dump(mode="json")
        immutable = {
            "finding_id": finding_id,
            "parent_run_id": parent.id,
            "action": action,
            "action_config": dict(body),
            "campaign_config": frozen,
        }
        # The audit event is intentionally before either durable action row.
        authorize(job_type, None, allowlist=config.target_allowlist, actor=actor,
                  writer=audit_writer, project_id=finding.project_id, run_id=run_id,
                  detail={"actor": actor, **immutable})
        session.add(Run(id=run_id, project_id=finding.project_id, target_id=parent.target_id,
                        mode="api", status="queued", scanner=f"ml.{action}",
                        created_by=actor, stage_table={"parent_run_id": parent.id, "jobs": {}}))
        session.add(Job(id=job_id, run_id=run_id, project_id=finding.project_id, type=job_type,
                        status="queued", created_by=actor, detail=immutable))
        session.flush()
        session.execute(campaign_table.insert().values(
            run_id=run_id,
            project_id=finding.project_id,
            target_id=parent.target_id,
            kind="attack",
            modality=frozen["modality"],
            parent_run_id=parent.id,
            config=frozen,
            limitations=[],
        ))
    try:
        from redsim.workers.tasks.ml_campaign import ml_campaign_run

        result = ml_campaign_run.delay(job_id)
        with get_session() as session:
            job = session.get(Job, job_id)
            if job is not None:
                job.celery_task_id = str(result.id)
    except Exception:  # durable queued row survives broker outages
        # Durable queued state is intentionally recoverable after broker loss.
        logger.warning("enqueue failed for finding action job %s", job_id, exc_info=True)
    return FindingJobHandle(run_id, [job_id])


# ---------------------------------------------------------------------------
# LLM probe findings (register LLM-15; plan 12 wave B2 llm-api)
# ---------------------------------------------------------------------------

#: ``Finding.source_tool`` of every probe finding.
LLM_SOURCE_TOOL = "redsim.ml/llm_probe"
#: The register names ``finding_type="adversarial_llm"``; ``redsim.schema.FindingType`` is a frozen
#: platform literal, so the value is used only once that literal carries it and ``adversarial_ml`` is
#: the stand-in meanwhile. ``schema_blob["finding_kind"]`` always says ``adversarial_llm``.
LLM_FINDING_KIND = "adversarial_llm"
LLM_FINDING_TYPE: str = (
    LLM_FINDING_KIND if LLM_FINDING_KIND in get_args(FindingType) else "adversarial_ml"
)
#: The label every probe finding carries for how its severity was chosen (spec 15.5 analogue).
LLM_SEVERITY_BASIS = "derived_from_hit_rate"
#: Hit-rate bands for the derived severity (register LLM-15): ``>= 0.5`` high, ``>= 0.2`` medium,
#: ``> 0`` low. Not the spec 15.5 ASR bands of image / tabular findings; labelled as such on the row.
LLM_SEVERITY_BANDS: tuple[tuple[float, str], ...] = ((0.5, "high"), (0.2, "medium"), (0.0, "low"))


def llm_severity_from_hit_rate(hit_rate: float | None) -> str | None:
    """The derived severity of a probe hit rate, or ``None`` when no hit was observed."""
    if hit_rate is None or hit_rate <= 0.0:
        return None
    for floor, label in LLM_SEVERITY_BANDS:
        if hit_rate >= floor and (floor > 0.0 or hit_rate > 0.0):
            return label
    return None


def _probe_rows(scorecard: Mapping[str, Any]) -> Iterator[tuple[dict[str, Any], dict[str, Any]]]:
    """``(probe row, family row)`` pairs of a scorecard's ``families`` block."""
    for family in scorecard.get("families") or []:
        if not isinstance(family, Mapping):
            continue
        for probe in family.get("probes") or []:
            if isinstance(probe, Mapping):
                yield dict(probe), dict(family)


def _primary_detector_row(probe: Mapping[str, Any]) -> dict[str, Any] | None:
    """The detector row a finding is projected from: the first ``run`` row with a denominator."""
    rows = [dict(d) for d in (probe.get("detectors") or []) if isinstance(d, Mapping)]
    primary = probe.get("primary_detector")
    ordered = sorted(rows, key=lambda d: 0 if primary and d.get("detector") == primary else 1)
    for row in ordered:
        if row.get("status", "run") == "run" and int(row.get("n_evaluated") or 0) > 0:
            return row
    return None


def llm_finding_title(probe_id: str, detector: str, n_hits: int, n_evaluated: int) -> str:
    """``LLM probe <probe> hit rate k/n (detector <d>)``: counts and ids only, never prompt text."""
    return f"LLM probe {probe_id} hit rate {n_hits}/{n_evaluated} (detector {detector})"


def llm_finding_description(
    *, probe_id: str, goal: str | None, detector: str, n_hits: int, n_evaluated: int, n_none: int,
    hit_rate: float, threshold: float, severity: str, model_id: str | None, persona: str | None,
    guardrail_mode: str | None, seed: Any, max_prompts: Any, garak_version: str | None,
) -> str:
    """Rules-generated measured summary with denominators (spec 5.7 analogue). No LLM, no prompt text."""
    parts = [
        f"Measured: garak probe {probe_id} ({goal or 'goal not recorded'}) fired detector {detector} on "
        f"{n_hits}/{n_evaluated} evaluated responses (hit rate {hit_rate:.4f}), crossing the finding threshold "
        f"{threshold:g}.",
        f"{n_none} response(s) could not be evaluated by the detector and are outside the denominator.",
        f"Severity {severity} is derived from the hit rate bands (>=0.5 high, >=0.2 medium, >0 low), not from "
        f"the spec 15.5 ASR bands; a hit means the detector fired, not a verified harm.",
        f"Target: model {model_id or 'not recorded'} behind persona {persona or 'not recorded'} with guardrail_mode "
        f"{guardrail_mode or 'unknown'}; seed {seed}, prompt cap {max_prompts} per probe, one generation per "
        f"prompt, garak {garak_version or 'version not recorded'}. Measured at these settings only.",
        "Prompts and responses are stored in the run's garak report artifacts and are not rendered here.",
    ]
    return " ".join(parts)


def project_llm_findings(
    session: Session,
    scorecard: Mapping[str, Any],
    *,
    run_id: str,
    project_id: str,
    target_id: str | None,
    threshold: float,
    artifacts: Mapping[str, str] | None = None,
    recommendations: Sequence[Mapping[str, Any]] | None = None,
    limitations: Sequence[str] | None = None,
) -> list[str]:
    """Project one ``Finding`` per probe whose hit rate crosses ``threshold`` (register LLM-15).

    The scorecard is the evidence authority: every field of the row is a count
    or an id read from it; nothing is generated and no prompt or response text
    is copied. ``scanner_finding_id`` is ``llm.<probe>.<detector>`` so the row
    is idempotent per run (an existing row is returned untouched, as
    :func:`project_campaign_findings` does). ``source_tool`` is
    ``redsim.ml/llm_probe`` and the severity is derived from the hit rate and
    labelled so (``schema_blob["llm"]["severity_basis"]``). Returns the finding
    ids in scorecard order.
    """
    from sqlalchemy import select

    from redsim.db.models import Finding

    model_id = scorecard.get("model_id")
    persona = scorecard.get("persona")
    guardrail_mode = scorecard.get("guardrail_mode")
    garak_version = scorecard.get("garak_version")
    settings = json.dumps({
        "model_id": model_id, "persona": persona, "seed": scorecard.get("seed"),
        "max_prompts_per_probe": scorecard.get("max_prompts_per_probe"),
        "detector_mode": scorecard.get("detector_mode"), "garak_version": garak_version,
    }, sort_keys=True)
    settings_hash = hashlib.sha256(settings.encode("utf-8")).hexdigest()
    projected: list[str] = []
    for probe, family in _probe_rows(scorecard):
        probe_id = str(probe.get("probe_id") or probe.get("id") or "")
        if not probe_id:
            continue
        row = _primary_detector_row(probe)
        if row is None:
            continue
        n_evaluated = int(row.get("n_evaluated") or 0)
        n_hits = int(row.get("n_hits") or 0)
        n_none = int(row.get("n_none") or 0)
        rate = row.get("hit_rate")
        hit_rate = float(rate) if isinstance(rate, (int, float)) else (n_hits / n_evaluated if n_evaluated else 0.0)
        severity = llm_severity_from_hit_rate(hit_rate)
        if severity is None or hit_rate < threshold:
            continue
        detector = str(row.get("detector") or "detector")
        scanner_id = f"llm.{probe_id}.{detector}"
        existing = session.execute(
            select(Finding.id).where(Finding.run_id == run_id, Finding.scanner_finding_id == scanner_id)
        ).scalar_one_or_none()
        if existing is not None:
            projected.append(str(existing))
            continue
        now = datetime.now(UTC).isoformat()
        title = llm_finding_title(probe_id, detector, n_hits, n_evaluated)
        description = llm_finding_description(
            probe_id=probe_id, goal=probe.get("goal"), detector=detector, n_hits=n_hits, n_evaluated=n_evaluated,
            n_none=n_none, hit_rate=hit_rate, threshold=threshold, severity=severity, model_id=model_id,
            persona=persona, guardrail_mode=guardrail_mode, seed=scorecard.get("seed"),
            max_prompts=scorecard.get("max_prompts_per_probe"), garak_version=garak_version,
        )
        recs = [dict(r) for r in (recommendations or []) if isinstance(r, Mapping)]
        llm_detail: dict[str, Any] = {
            "probe_id": probe_id,
            "short_id": probe.get("short_id") or probe_id,
            "family": family.get("family") or probe_id.split(".", 1)[0],
            "goal": probe.get("goal"),
            "tier": probe.get("tier"),
            "detector": detector,
            "detector_status": row.get("status", "run"),
            "n_evaluated": n_evaluated,
            "n_hits": n_hits,
            "n_passed": row.get("n_passed"),
            "n_none": n_none,
            "hit_rate": hit_rate,
            "ci_lower": row.get("ci_lower"),
            "ci_upper": row.get("ci_upper"),
            "n_prompts_sent": probe.get("n_prompts_sent"),
            "threshold": threshold,
            "severity": severity,
            "severity_basis": LLM_SEVERITY_BASIS,
            "severity_bands": {"high": ">= 0.5", "medium": ">= 0.2", "low": "> 0"},
            "model_id": model_id,
            "gateway_host": scorecard.get("gateway_host"),
            "persona": persona,
            "guardrail_mode": guardrail_mode,
            "garak_version": garak_version,
            "seed": scorecard.get("seed"),
            "max_prompts_per_probe": scorecard.get("max_prompts_per_probe"),
            "detector_mode": scorecard.get("detector_mode"),
            "detectors": [dict(d) for d in (probe.get("detectors") or []) if isinstance(d, Mapping)],
            "artifacts": dict(artifacts or {}),
            "recommendations": recs,
            "limitations": list(limitations if limitations is not None else (scorecard.get("limitations") or [])),
            "review": FindingReview().model_dump(mode="json"),
        }
        evidence = {"scorecard_rows": [f"llm.{probe_id}.{d.get('detector')}" for d in llm_detail["detectors"]],
                    "scorecard_artifact": (artifacts or {}).get("scorecard")}
        finding = RedsimFinding(
            id=scanner_id,
            title=title,
            severity=cast("Any", severity),
            finding_type=cast("Any", LLM_FINDING_TYPE),
            description=description,
            source_tool=LLM_SOURCE_TOOL,
            source_run_id=run_id,
            affected_component=str(target_id or model_id or "llm-target"),
            target=str(model_id) if model_id else None,
            confidence="medium" if n_evaluated >= 30 else "low",
            status="open",
            created_at=now,
            updated_at=now,
            evidence=json.dumps(evidence, sort_keys=True),
            references=None,
            artifact_path=(artifacts or {}).get("scorecard"),
            remediation_steps=finding_remediation_steps([
                CandidateRecommendation.model_validate(r) for r in recs
                if isinstance(r, Mapping) and r.get("triggered_by")
            ]) if recs else None,
        ).model_dump(mode="json")
        finding["finding_kind"] = LLM_FINDING_KIND
        finding["llm"] = llm_detail
        db_row = Finding(
            id=str(uuid4()), scanner_finding_id=scanner_id, run_id=run_id, project_id=project_id,
            schema_blob=finding, status="open", severity=severity, source_tool=LLM_SOURCE_TOOL,
            validation_state="unvalidated",
            dedup_key=f"llm:{str(model_id or '')[:32]}:{probe_id}:{detector}:{settings_hash[:16]}",
        )
        session.add(db_row)
        session.flush()
        projected.append(db_row.id)
    return projected


def read_llm_finding_detail(schema_blob: dict[str, Any] | None) -> dict[str, Any] | None:
    """The ``llm`` block of a probe finding, or ``None`` for a campaign finding."""
    if not schema_blob:
        return None
    block = schema_blob.get("llm")
    return dict(block) if isinstance(block, dict) and block else None


__all__ = ["DISMISSABLE_FROM", "DISMISSED_STATUS", "LLM_FINDING_KIND", "LLM_FINDING_TYPE",
           "LLM_SEVERITY_BANDS", "LLM_SEVERITY_BASIS", "LLM_SOURCE_TOOL", "FindingJobHandle",
           "MLFindingAdmissionError", "build_finding_detail", "create_finding_action_job",
           "finding_description", "finding_measurements", "finding_observations",
           "finding_remediation_steps", "finding_title", "llm_finding_description", "llm_finding_title",
           "llm_severity_from_hit_rate", "project_campaign_findings", "project_llm_findings",
           "read_finding_detail", "read_llm_finding_detail"]
