"""Prepend the plain-language lead to findings written before it existed.

    redsim-run api python scripts/backfill_finding_descriptions.py [--dry-run]

Reads every finding whose ``schema_blob.description`` does not start with
"What happened:" and rebuilds the lead from the numbers already stored on the
finding (``schema_blob.ml`` for evasion findings, ``schema_blob.llm`` for LLM
probe findings), using the same functions the projection uses for new
findings. The measured text that was there stays after the lead. Nothing is
generated by an LLM and no number is invented: a finding without the counts
gets the generic lead.
"""
from __future__ import annotations

import os
import sys

from sqlalchemy.orm.attributes import flag_modified

from redsim.db.models import Finding
from redsim.db.session import get_session, init_engine
from redsim.services.ml_findings import evasion_plain_language, llm_plain_language

LEAD = "What happened: "
_DOMAIN_BY_ATTACK = {"word_substitution": "text", "dpatch": "detection", "patch_noise_control": "detection"}


def _same(a: float | None, b: float | None) -> bool:
    return a is not None and b is not None and abs(float(a) - float(b)) < 1e-9


def _eps(m: dict) -> float | None:
    params = m.get("params") or {}
    value = m.get("eps", params.get("eps"))
    return float(value) if value is not None else None


def evasion_lead(ml: dict, blob: dict) -> str:
    rows = [m for m in ml.get("measurements") or [] if isinstance(m, dict)]
    first_eps = ml.get("first_success_eps")
    first = next((m for m in rows if m.get("family") == "evasion" and m.get("attack_id") == ml.get("attack_id")
                  and _same(_eps(m), first_eps)), None)
    clean = next((m for m in rows if m.get("family") == "clean"), None)
    control = next((m for m in rows if m.get("family") == "control" and _same(_eps(m), ml.get("reference_eps"))), None)
    domain = blob.get("target_domain") or _DOMAIN_BY_ATTACK.get(str(ml.get("attack_id")))
    return evasion_plain_language(
        attack_id=str(ml.get("attack_id") or ""), attack_name=str(ml.get("attack_name") or ml.get("attack_id") or "the attack"),
        domain=domain, eps=float(first_eps) if first_eps is not None else None, norm=str(ml.get("norm") or "linf"),
        n_clean_correct=(first or {}).get("n_clean_correct"), n_flipped=(first or {}).get("n_flipped_from_clean"),
        threshold=float(ml.get("threshold") or 0.2),
        control_n_correct=(control or {}).get("n_correct"), control_n=(control or {}).get("n"),
        clean_n_correct=(clean or {}).get("n_correct"), clean_n=(clean or {}).get("n"),
    )


def llm_lead(llm: dict) -> str:
    return llm_plain_language(
        probe_id=str(llm.get("probe_id") or "probe"), goal=llm.get("goal"),
        n_hits=int(llm.get("n_hits") or 0), n_evaluated=int(llm.get("n_evaluated") or 0),
        threshold=float(llm.get("threshold") or 0.2),
    )


def main(argv: list[str]) -> int:
    dry = "--dry-run" in argv
    init_engine(os.environ["REDSIM_DB_URL"])
    changed = skipped = 0
    with get_session() as session:
        for finding in session.query(Finding).all():
            blob = dict(finding.schema_blob or {})
            old = str(blob.get("description") or "")
            if old.startswith(LEAD):
                skipped += 1
                continue
            if isinstance(blob.get("llm"), dict):
                lead = llm_lead(blob["llm"])
            elif isinstance(blob.get("ml"), dict):
                lead = evasion_lead(blob["ml"], blob)
            else:
                skipped += 1
                continue
            blob["description"] = f"{lead} {old}".strip()
            if not dry:
                finding.schema_blob = blob
                flag_modified(finding, "schema_blob")
            changed += 1
        if dry:
            session.rollback()
    print(f"findings updated: {changed}, left as they were: {skipped}{' (dry run)' if dry else ''}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
